### ISSUE TITLE
Not compatible with Nextcloud 12

### ISSUE THREAD

**Issue by io-node** [fcturner/sharerenamer#15]
As of NC 12 the app doesn't function as expected. Changing the app info to max-version 12 does make it visible but unable to rename the shared link.

**Comment by MichaIng** [comment]
The reason is that IDb support was dropped in nextcloud 12 and the app still uses it e.g. /db/sharerenamermapper.php.

This also leads to an AppName resolve error in the nextcloud log. API changes can be seen here: https://docs.nextcloud.com/server/12/developer_manual/app/changelog.html#id2

**Comment by mikerockett** [comment]
@fcturner Will support for this be added soon. Rely relying on this...

**Comment by rayfun** [comment]
Don't think anything is going to happen here as well...
https://github.com/fcturner/passwords/issues/323

**Comment by mikerockett** [comment]
@rayfun - Guess the same would apply to this. I'm quite disappointed, but won't express anything here so as to prevent said war. Hopefully someone else makes an addon-app for NC as I really do need it. I'm not sure how to write NC apps yet, but might land up looking into it if I find the time.

**Comment by rayfun** [comment]
@mikerockett this fork fixes compat for NC 12 https://github.com/LazyShpee/sharerenamer

**Comment by mikerockett** [comment]
@rayfun - You are a legend. Thank you!

**Comment by hallbob** [comment]
Thanks for this info !

**Comment by Aasemoon** [comment]
Hi there, 
Thanks a lot for the fork, it allowed me to install the app which was otherwise not possible to enable on NC 12. However I have a weird issue, Somehow every time I try to generate a share link, the "password protect" option is automatically selected and I can't seem to deselect it! Basically I have to disable the app every time to disable password protection. This is pretty strange behaviour and I can't figure out why it's happening. [This is independant of the browser et al..]
Any ideas?

**Comment by jancborchardt** [comment]
@LazyShpee @fcturner could you make sure the fix from the fork also makes it to the main app? :) We could even move the repository to the Nextcloud organization at https://github.com/nextcloud so you both can manage the repository. :)

cc @schiessle @rullzer for technical info on this issue and Nextcloud sharing.

**Comment by fcturner** [comment]
> We could even move the repository to the Nextcloud organization at https://github.com/nextcloud so you both can manage the repository. :)

**Absolutely not:** [passwords#323](https://github.com/fcturner/passwords/issues/323).

That goes for this app too. I'm sorry. I'm glad I could be of a help creating this app.

Please use the fork of LazyShpee if you are using NextCloud, and hope he will maintain it. My next version of this app will be ownCloud only.

**Comment by jancborchardt** [comment]
@fcturner hm, sorry to hear that. :( Especially as I always tried to help you and gave feedback, also partly as being designer for Nextcloud (formerly ownCloud) – which I haven’t seen anyone from ownCloud do.

As you wrote in the other issue:

> This is of course a personal choice. My main reason is that I absolutely resent the way how former ownCloud CTO Mr. Karlitschek ran away with the code that not only was committed by the ownCloud team, but also by volunteers like myself. It might be legal, to me it feels like theft and betrayal.

This seems to be a misunderstanding of the project, the fork, and the AGPL. Frank founded ownCloud back in the day, and other people like me were early contributors even before the company existed. The reason for the fork is actually that a lot of code was _not_ made open source, and that the core server requires you to sign a Contributor License Agreement (CLA) which ensures that ownCloud Inc (or rather GmbH, since the Inc went away) will always have full copyright for the code. And that’s an issue since this depends a lot on VC funding … not very sustainable, that’s also why I personally, and most other developers, quit.

One big reason for the fork was to make sure the code will still be there and open in the future. That’s why _everything_ is AGPLv3+. We didn’t »_run away_« with the code. We made sure it’s freed forever for the community. All our hearts are beating for free & open source software, and that’s why we made this difficult decision last year. Don’t think that it was only the actions of one person – it was a general unrest which culminated in the fork. And if you look at the repository statistics, you can easily see which is the more active project.

We really care about community, we organize meetups, we organize the yearly conference, we make our developer meetings open for anyone to attend and give travel funding to contributors so we can all work together on building a useful piece of software – on a sustainable and community-driven basis rather than just for profit and selling.

Hope that explains it a bit more.
