### ISSUE TITLE
Publish on nextcloud store

### ISSUE THREAD

**Issue by bugzy** [fcturner/sharerenamer#3]
Just wondering if you would be willing to publish this app on the nextcloud store, which is currently in beta. I currently use the app without issues on Nextcloud 10. See https://apps.nextcloud.com

**Comment by fcturner** [comment]
Yeah, well, let them first make thing a lot easier [than this](http://nextcloudappstore.readthedocs.io/en/latest/developer.html#publishing-apps-on-the-app-store). Ridiculous amount of work to do. That's one.

Two, using app stores gives the owner of the app stores track of every upload by me and download by you, server info of me and you. They don't have a privacy statement with info about the purpose of these data. Thinking they wouldn't be analysing your steps would be naïve I guess. So I'm sorry, but this is too Google-like to me.

**Comment by fcturner** [comment]
Just use **git** and nobody knows about your moves, and it places the app immediately on the right place on your server:

(assuming `/var/www/owncloud/` as your root location)
 ```sh
rm -rf /var/www/owncloud/apps/sharerenamer
git clone https://github.com/fcturner/sharerenamer.git /var/www/owncloud/apps/sharerenamer
```

Couldn't be much easier.

**Comment by jancborchardt** [comment]
cc @BernhardPosselt @LukasReschke for info on the above statements. Cause it would be cool to have this app on the store.

**Comment by fcturner** [comment]
Nice idea, but I don't like that idea. There's no privacy statement, and I don't like one-way policies where app stores can track my moves (who knows?) but I can't track theirs. Not much of an App Store fan... 
I'm not even a NextCloud fan, giving the fact that I'm solving multiple issues for my other app (Passwords) to support NC11 because you lack to document notes for app developers. I have to let others down because they migrated to NextCloud. And I really don't like *that*. 

I'm sorry, I'm a bit frustrated about that at the moment. Maybe I'll find NC useful over OC in the new year. For now, I certainly don't. I hear others complaining constantly about the same. NC11 is just premature in my opinion. 

Thanks anyway for your time. The intention is OK.

**Comment by BernhardPosselt** [comment]
Code is open source and we gain nothing from tracking you (why would we care about which IP uploads an archive? Besides it's on github anyways). There's no privacy statement (yet?) Because there's no tracking so no one came up with an the idea of adding one. Apart from that the European data privacy laws are pretty good. 

Downloads are not tracked because we don't host the archive and no request is made when installing an archive. You give us a download URL and the user downloads it exactly from there. The only thing that we offer is a json dump which you can even download once and place in a folder locally if you're paranoid. That's all, the api is just 4 json files in a folder.

As for complicated: we only require you to obtain and sign the release everything else is done for you. We do that to ensure that in case of a security vulnerability on our server no one can upload a modified archive for an app and endanger users. Pretty much every Linux distro does this as well. You generate and get the signed certificate once and afterwards it's one command which can easily be scripted.

As for git: sure it's nice but most users don't know git or can't use it on their servers because webhosting.

**Comment by jancborchardt** [comment]
Any update @fcturner?
I hope that @BernhardPosselt’s explanation cleared things up. Most of the ownCloud contributors and community switched to Nextcloud so it would be awesome to have you too. :) We’d love to spread the word about your app too if it’s in the app store.
