### ISSUE TITLE
Renamed links gone after nextcloud update

### ISSUE THREAD

**Issue by zguithues** [fcturner/sharerenamer#9]
This is a great plugin!  

I'm using it with my insurance agency.  We're creating custom shared links for clients, as a one-stop-shop for their policy documents.

The only issue i've come across is that every time i update Nextcloud, all my renamed links are gone.  Is there any way to retain the links through nextcloud updates?

**Comment by fcturner** [comment]
Thanks!

If NextCloud removes all your shares from the database, then I cannot do anything about it. My plugin only replaces the token in the database, more specifically the table `oc_share`. So, I don't know how NextCloud handles that, but it shouldn't make a difference.

One thing, I'm avoiding NextCloud because of many failures and bugs like this. I think ownCloud is far more robust at the moment.
